### ISSUE TITLE
Actualidad/Actividad Funcionalidad

### ISSUE THREAD

**Issue by jaliaga-devcenter** [jaliaga-devcenter/sede#37]
En el master en el folder noticias hay un template llamado actualidad. Ahora es estático pero tiene que ser dinámico y mostrar las noticias. Además hay que crear un template para que cuando pulses a ver más se vea la noticia entera.

En el controller NoticiasController está el método. Falta completarlo con la lógica

**Comment by jsober** [comment]
Tarea realizada y probada.
actualidad muestra o todas las noticias o solo una.

**Comment by jaliaga-devcenter** [comment]
En el master no funciona bien. Cuando le doy a las noticias me sale sin estilo

**Comment by jaliaga-devcenter** [comment]
Me da el siguiente error:

Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1

La noticia es:

<p>Esto es una prueba&nbsp;<strong>de una noticia</strong></p>

<p>&nbsp;</p>

<p><strong>Esto es un parrafo</strong></p>

<p>Otro parrafo</p>

<p>&nbsp;</p>

<p>&nbsp;</p>

<p>&nbsp;</p>

**Comment by jsober** [comment]
En el crud de noticias puse un límite para mostrar solo 99, lo voy a quitar y que solo aparezca título y fecha.

En acutalidad busca , pero ¿que ocurre si no esta? que falla, voy a arreglarlo.
