### ISSUE TITLE
Corregir los enlaces que hay en mapa Web

### ISSUE THREAD

**Issue by jaliaga-devcenter** [jaliaga-devcenter/sede#38]
en el mapa-web los enlaces no son correctos. Hay que corregirlos.

Cualquier duda me preguntas porque en teoría están todos creados.

**Comment by jsober** [comment]
Enlaces a corregir:
- Tablón de anuncios
- Notifica
- Carpeta ciudadano
- Perfil del contratante (falta funcionalidad)

- Solicitar información y contacto (misma url)

- Acceso ciudadano

**Comment by jaliaga-devcenter** [comment]
@jsober  a que te refores con que en el perfil del contratante falta funcionalidad?
