### ISSUE TITLE
Paradas programadas

### ISSUE THREAD

**Issue by jaliaga-devcenter** [jaliaga-devcenter/sede#46]
Añadir  nuevo campo a la entidad parada que sea de tipo fecha (fecha)
Adaptar el crud.

En la página siguiente:

http://localhost:8081/sede/paradas-programadas

Mostrar el listado de paradas programadas siempre y cuando la fecha no haya pasado.

**Comment by jsober** [comment]
fixed.
Solo fecha
Listado muestra desde ese día en adelante. no muestra anteriores.
Movida lógica de la seccion a paradasController
